### ISSUE TITLE
xlsx download error with Date type field

### ISSUE THREAD

**Issue by danke02** [olifolkerd/tabulator#1153]
Hello.
When I tried to download table data in Xlsx format, I met an error something like below.
```
modules.js?hash=b64b2df440897f34ff9353394dc3afaa8cd223fc:127899 Uncaught TypeError: s.t.match is not a function
    at write_sst_xml (modules.js?hash=b64b2df440897f34ff9353394dc3afaa8cd223fc:127899)
    at write_sst (modules.js?hash=b64b2df440897f34ff9353394dc3afaa8cd223fc:134886)
    at write_zip (modules.js?hash=b64b2df440897f34ff9353394dc3afaa8cd223fc:139876)
    at write_zip_type (modules.js?hash=b64b2df440897f34ff9353394dc3afaa8cd223fc:140019)
    at Object.writeSync [as write] (modules.js?hash=b64b2df440897f34ff9353394dc3afaa8cd223fc:140124)
    at Download.xlsx (modules.js?hash=b64b2df440897f34ff9353394dc3afaa8cd223fc:111680)
    at Download.download (modules.js?hash=b64b2df440897f34ff9353394dc3afaa8cd223fc:111221)
    at $.(anonymous function).(anonymous function).download (http://172.28.203.98:3000/packages/modules.js?hash=b64b2df440897f34ff9353394dc3afaa8cd223fc:108798:36)
    at $.(anonymous function).(anonymous function).download (http://172.28.203.98:3000/packages/modules.js?hash=b64b2df440897f34ff9353394dc3afaa8cd223fc:70575:25)
    at HTMLDivElement.<anonymous> (modules.js?hash=b64b2df440897f34ff9353394dc3afaa8cd223fc:70687)
```

I figured out that Date type field was a problem. When tabulator converts row data to excel related data, it cares only number and boolean type, and treats other types like Date type as string type. (xlsx() > generateSheet() > rowsToSheet() function)
When jssheet build shared string table for creating xlsx document it fails to call member function named "match" because Date type doesn't have this function. I used downloadDataFormatter option to convert Date type data to string.

**Comment by olifolkerd** [comment]
Hey @danke02 

Thanks for the info. 

That looks more like an issue in the XSLX dependency that Tabulator. i will update the documentation to warn users of the situation and suggest your work around.

Thanks

Oli :)

**Comment by danke02** [comment]
@olifolkerd 
There will be two solutions.
1. Warn users to always convert any data of non number, boolean,string type to string with downloadDataFormatter option.
2. In the rowsToSheet() function, assign excel related data value of non number,boolean type with toString() method.
3. Set type of excel related data as correct data type like "d" for Date. And call toString() method for any data type other than string, number, Date.

I think the third will be the best practice for users.

Thanks for your great product.

Sungjin.

**Comment by olifolkerd** [comment]
Hey @danke02 

I have just pushed a patch to the master branch that uses xlsx library's inbuilt sheet_add_aoa function, which should correctly parse in dates.

It will be included in this evenings patch release.

Cheers

Oli :)

**Comment by runawaycoin** [comment]
Hi, i still have a problem trying to get a date to be recognised by Excel.

This PR resolves it for me https://github.com/olifolkerd/tabulator/pull/1841 

Now in my accessorDownload function if i return a Date object - it is formatted by sheetsjs / excel as a date field.

Not sure how otherwise to do it.

**Comment by olifolkerd** [comment]
Hey @runawaycoin 

Thanks for the pull request, i will review it at the weekend and include it in the next patch release if it works out.

Cheers

Oli :)

**Comment by masoodqss** [comment]
This bug still persists. Tried everything from converting numbers to string. Still same bug
