### ISSUE TITLE
Memory Leak v4.1.2

### ISSUE THREAD

**Issue by OOnogul** [olifolkerd/tabulator#1709]
A memory leak is causing performance problems after clearing header filters 5-6 times. Memory is increasing exponentially when called these two functions:
- `.clearHeaderFilter()`
- `.clearFilter(true)`

Version: 4.1.2
Browser: Chrome v67.0.3396.87

**To Reproduce**
1. Go to call any of the functions that is stated above.
2. To see the problem better, call the functions a couple of times because each operation duplicates some elements and arrays.
3. Inspect table.modules.filter to see two variables; `headerFilterColumns`, `headerFilterElements`. See the duplicating issue. Also see table.modules.localize.bindings, there is also the same problem.
4. There is more duplications that I cannot find.
5. Chrome snapshot indicates the `Detached HTMLInputElement`, `Detached InternalNode` and `Detached EventListener` is taking a lot of memory.

I don't want to misguide but I have tracked the issue to `generateHeaderFilterElement()` where said arrays are having been pushed without deleting old elements.

Thanks in advance. Love the tabulator. Keep up the good work. 👍

**Comment by Rodbjartson** [comment]
What a catch! This is gold! 100 thumbs up

**Comment by olifolkerd** [comment]
This was fixed in the 4.1.5 release at the weekend

**Comment by dcanning** [comment]
I'm still getting this in 4.2.7:
https://plnkr.co/edit/Bf1mZKA312YdSZQiLHmO

click the clear filter 10-12 times, browser tab will freeze up.

**Comment by richard-slabbert94** [comment]
Hi Oli,

Once again thank you for your great component.

Any news on the memory leak?  I am using 4.4.1 and am running into this issue with `.clearHeaderFilter()`.

Richard
