### ISSUE TITLE
ajaxURL and memory usage

### ISSUE THREAD

**Issue by noluckman** [olifolkerd/tabulator#1723]
**Describe the bug**
Each time i am using the replaceData function on my table the memory increase of 0.4Mo. So after 1 day the memory on the web browser tab is more than 450Mo

**Tabulator Info**
- Tabulator 4.1.5
- Post a copy of your construct object if possible so we can see how your table is setup
var jtableOEE = new Tabulator("#tableOEE", {
                layout: "fitColumns",
                history: false,
                height: "85vh",
                ajaxURL: "./PESRest/PCO/LTE/ALL/PRODUCT",
                columns: [
                    {title: "Product Name", field: "productdesc", headerSort: false, widthGrow: 1},
                    {title: "Workstation", field: "pn", headerSort: false, widthGrow: 3},
                    {title: "OP. Runtime", field: "runtime", headerSort: false},
                    {title: "Target", field: "target", align: "center", headerSort: false},
                    {title: "OK", field: "goodparts", align: "center", headerSort: false},
                    {title: "NOK", field: "nokparts", align: "center", headerSort: false},
                    {title: "On Hold", field: "onhold", align: "center", headerSort: false},
                    {title: "Down. NP", field: "notplanned", align: "center", headerSort: false},
                    {title: "Down. P", field: "planned", align: "center", headerSort: false},
                    {title: "Efficiency", field: "efficiency", headerSort: false, align: "center"}
                ]
            });

**To Reproduce**
jtableOEE.replaceData(); is call in a function called using websocket.
When i just disable jtableOEE.replaceData() function no memory change but each time the function is called memory is increasing.

**Expected behavior**
Less memory usage

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 7
 - Browser Chrome
 - Version  71.0.3578.98

**Additional context**

**Comment by olifolkerd** [comment]
Hey @noluckman 

Thanks for getting in touch, sorry to hear you are having issues. I can certainly look into the cause of that.

Could you tell me how many rows roughly your table is to start with and roughly how many rows you are passing into the ***replaceData*** function each time?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Thanks for the details, that is very helpful,

I will make sure this is fixed for the 4.2 release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
To give you an update on this, i have identified several areas where DOM elements were not being cleared and i am in the process of working through different configurations of the table to ensure i have found them all.

I should have a fix for this in the next patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
I have released version 4.2.5 which includes some initial fixes for the memory leak.

Let me know how you get on with it.

Cheers

Oli :)

**Comment by Arnaud92BlR** [comment]
Hello,

Following #1953, I've upgraded to 4.2.5 and still have the issue.
I've attached a small test that shows the problem (at least on edge). Hope that it helps !

Thanks for your effort, regards,
Arnaud

[leak.zip](https://github.com/olifolkerd/tabulator/files/3054546/leak.zip)

**Comment by olifolkerd** [comment]
Hey @Arnaud92BlR 

Thanks for the feedback, i will have a look into that as well.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Arnaud92BlR 

Are you still seeing the issue in the latest version of Tabulator?

Cheers

Oli :)

**Comment by greenscreens-io** [comment]
Hi, 

Still, @pallavikhandekar is right. Hope this will help....

Indeed, there is a major leak issue due to passing **var self=this** to the internal closures on many places.
This can be easily checked with heap snapshot. After calling table.clearData(), there will be a lot of detached node elements.
[More here](https://developer.chrome.com/devtools/docs/heap-profiling-dom-leaks)

Simple solution is to use **let** instead of **var**.
**let** will be auto-released after exiting context, while **var** stays locked inside closure and never released.

```
RowManager.prototype.setData = function(data, renderInPosition, columnsChanged) {
 
    // var self = this;

    let self = this;
    return new Promise((resolve, reject) => {  
             self....something
     });
}
```

...also, it is unecessary to iterate DOM nodes and remove them,
just leave it to GC as native code is much faster than removing nodes through JavaScript. 

instead of 
```
while (this.element.firstChild) this.element.removeChild(this.element.firstChild);
```

this is enough, and much faster
```
this.element.innerHTML = '';
```

**Comment by olifolkerd** [comment]
Hi @greenscreens-io 

Thanks for your feedback,

There is certainly some improvement that can be made there, however it is not down to the variable definitions but down to the event handlers not being properly released when the elements are detached from the DOM, which is preventing the nodes from being correctly garbage collected, it is on the roadmap in the next release to improve this functionality

Switching between ***var*** and ***let*** will make no difference to the garbage collection of the variables. their primary difference is related to scope, var is a function level scope, accessible inside the function it is declared (but importantly not outside) where as let is block level accessible only inside the logic statement it is declared which is great for more optimal optimal code inside loops *(for for example)* but will make no difference in the example you specified above. There is no way for the var variables to be accessed outside the function and they are garbage collected after all internal functionality has been resolved, the reason for their persistence is when nodes linked back to them with event handlers persist then that scope remains persistent, which would be the case regardless of a choice of var or let.

The use of self variables was standard practice for passing scope before the advent of arrow functions, and is in fact what the bable transpiler actually does behind the scenes when converting es6 JavaScript to something more ES5 compatible

The best way to improve performance from a variable definition point of view is actually to be defining some elements of the table using ***const*** which is on the roadmap for the 5.0

And actually from a performance point of view the while loop removal method has been shown to offer much better performance than the innerHTML approach. There are substantial documentation explaining this on the web, and the jQuery library actually uses the while approach too because it is much more performant.

Cheers

Oli :)

**Comment by greenscreens-io** [comment]
Hi @olifolkerd 

MS IE will have listeners leak issue, as pointed in [stackoverflow](https://stackoverflow.com/questions/6033821/do-i-need-to-remove-event-listeners-before-removing-elements), but not in modern browsers. Detached DOM nodes will deactivate event listeners automatically, while GC can auto-clear **let** variables in closures compared to **var** which will never be cleared. 

In original code, "self" is referenced in underlying promise inside top function making it a closure. This prevents GC clearing variable referencing dom element. As dom is referenced in non-accessible variables, it can't be cleared by GC preventing  listeners auto-cleanup also.

More info can be found in great IBM document [here](https://www.ibm.com/developerworks/web/library/wa-memleak/wa-memleak-pdf.pdf) and in other places as [here](https://www.ditdot.hr/en/causes-of-memory-leaks-in-javascript-and-how-to-avoid-them). (2. and 4. ), and [here](https://www.tutorialspoint.com/if-a-dom-element-is-removed-are-its-listeners-also-removed-from-memory-in-javascript)

I've made simple test by adding 10k rows, call clearData, add 10k rows again... repeat many times, and check memory. In my tests, after loading 50k records through websocket in batches of 100recs, memory goes to 2.5GB and even manually triggering GC didn't help.

Tabulator would consume more and more memory without releasing detached nodes. This is not easy detectable with small amount of data or on web pages which reloads. But on SPA, this leak significantly slows down app over the time as it is being used.

After simple changes from **var** to **let**, repeat the test.  Memory will stay consistent. It will be possible to load 1m. records easily. It is really easy to confirm how **let** versus **var** affects GC behaviour. 

Actually, **_node.textContent = '';_** or  **_while (node.firstChild) {node.removeChild(node.lastChild);}_** should be the fastest depending on browser engine. It is always faster to remove last element from array than first element :) while textcontent will not trigger html parser.

However, .innerHTML = "" or textContent = "" only needs to clear the element content. And it clears the content in native code, whereas the while loop constantly crosses js/dom boundary. So it is expected to be faster. Some browser engines have custom handling in a case innerHTML is set to blank as a special case, we could verify this from e.g. webkit source.

**Comment by olifolkerd** [comment]
Hey @greenscreens-io 

If you have a test case that demonstrates the efficiency improvement of a `var` to `let` change in key areas then I would be happy to see it in action *(a JS Fiddle with both approaches loaded or similar)*. and would welcome a PR if you can show the difference.

I conducted my own experiments with the `innerHTML` vs `while` approach when i was building v 4 of tabulator and the `while` approach proved to be faster, i would not be looking to change this at the moment as any gains would be browser specific and it would just be sacrificing one point of view for another.

Cheers

Oli :)

**Comment by greenscreens-io** [comment]
Hi @olifolkerd 

Only way to detect this is manual analysis as you will have to create heap snapshot every time data is added to the table and then compare snapshots for detached nodes. In original tabulator version you will see increase in number of nodes as memory also, clicking on GC to force it, nothing will happen. Calling table.clearData(), forcing GC, creating snapshot will show the same detached nodes as in previous snapshot.

In modified version with **let**, repeating the steps will not show detached nodes at all and memory usage will be normal.

All I've done is to change **var** to **let** inside all functions containing **new Promise**.

Alternative approach just cross my mind might be this ... 

``
RowManager.prototype.setData = function(data, renderInPosition, columnsChanged) {
 
    var self = this;

    return new Promise((resolve, reject) => {  
             try {
                 ... do your stuff
            } finally {
                 self = null;
            }
     });
}
``

**Comment by olifolkerd** [comment]
Hey @greenscreens-io 

Im confused, 

You say you have already done this and profiled it. In which case could you not simply include your custom build in a JS fiddle and share a link, i would be happy to look at the heap snapshot of your improved example.

There are hundreds of promised based function closures in Tabulator, so have you targeted specific ones.

I would also be very interested to see how you have run the build system, as it automatically removes the `let` definitions and arrow functions when babel transpiles the source to ES5 when generating the minified source, so i would be surprised to see them in the final library.

Cheers

Oli :)

**Comment by greenscreens-io** [comment]
Hi @olifolkerd 

Will try to make long story short as possible 😊 and hope will mange to explain.

I'm aware of babel build `let` removal, however I did not use babel :) That’s’ the reason why alternative approach from my last post might be helpful. For library testing purposes, I’ve only changed non-minimized tabulator.js by replacing `var` to `let` in about 12 places and continue stress testing. I assume, it would be useful to switch to babel 7?!

During stress test, over prolonged usage time with many (setData, clearData, setData, cleardata calls) browser become very sluggish. Turns out, browser memory grows to 2,5GB and never released. After quick debugging and heap snapshot testing it turns out DOM nodes are not released in tabulator. 

I’ve found it is related to functions containing closures as callbacks from `new Promise` (there are 33 of them, not hundreds), and only those with circular referenced variables holding DOM node. (I asume it is valid for other values also, explanation below)

**Why?**

Let’s take this for an example….
```
  RowManager.prototype.scrollToRow = function (row, position, ifVisible) {
    let rowIndex = this.getDisplayRows().indexOf(row),
        **rowEl** = row.getElement(),
        rowTop,
        offset = 0;
    return new Promise((resolve, reject) => {
        …. rest of the code using **rowEl**
    }); } 
```
- **rowEl** from example above has a circular reference between scrollToRow and promise callback. This creates closure within scrollToRow (closure stays referenced, read below why)

- **scrollToRow** function belongs to RowManager instance which belongs to upper instance all the way to tabulator instance. Because this function is referenced, closure within will never be cleared as along as RowManager instance is referenced to tabulator instance and as long as tabulator instance is alive (has a reference). 

So, rowEl from example above has a circular reference in a function (closure) which is inside referenced function in a chain to tabulator instance. huhhh 😊 

That’s the reason GC can’t clear them. 

I'm not 100% sure, but it looks that in every call to scrollToRow, there is a leak, heap will show number of closure counts increase over time. Because it is a closure, you can’t inspect it and it is visible as a ghost function in memory snapshot. 

`var` in closures are never released as long as closure is “alive”, referenced as in this case within live function (RowManager instance). As rowEL keeps virtual DOM element, it is also never released. 

Having `var` in closure is common old technique to have a private (like In Java for example), but when `let` is used, GC behaves differently, and it is smart enough to realize ghost closure can be released.

I did not examine all the cases in tabulator, but very simply put, where is a function within a function containing variable with a circular reference (self, me, etc.), it is a closure. If closure is referenced, it can't be cleared, and circular variables will not be cleared also, thus keeping detached nodes in memory and thus not clearing event listeners.

Setting null to vars holding DOM node inside try-final within callback, will allow GC to clear detached nodes, but maybe not ghost closures, further testing is required for that. 

List of functions where I've simply replaced `var` keyword.

ColumnManager.prototype.scrollToColumn
RowManager.prototype.scrollToRow
RowManager.prototype.setData
RowManager.prototype.addRows
Row.prototype.updateData
Tabulator.prototype.updateData
Tabulator.prototype.updateOrAddData
Ajax.prototype.sendRequest
Page.prototype.setPage
Page.prototype.trigger
Page.prototype._getRemotePage


P.S. I think that, [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) might be used instead of promises on some places. It's worth investigating. Or maybe switching to async functions instead of `new Promise` constructs. And then trying with babel 7 to transpile into ES5 for older browsers.

**Comment by greenscreens-io** [comment]
Hi,

I've did more testing, and found some wierd behaviour. 

When testing just tabulator instance and simple addData, clearData, all is fine, no issues.

I na real scenarion, data I'm receiving is binary gzip compressed, and decompressed inside browser with [wasm-flate](https://www.npmjs.com/package/wasm-flate).

For live testing - data is loaded in batches of 100recs through websocket, decompressed with wasm-flate, decoded with TextDecoder, and loaded in tabulator. In such case, GC does not clear DOM nodes memory for some reason, and there is a lot of detached nodes. Only solution that worked for me was using `let`. Only then, variables will be cleared upon exiting from the context and all other references will be cleared. 

As soon as I swiched from binary websocket message to text-json, and stoped using compressed binay and wasm-flate , all is ok back again. No memory issues.

In the first place, I've tested wasm-flate alone, without any issues. This lib is used quite a lot so I don't think it is directly related but some combination of above.

**Comment by olifolkerd** [comment]
Hey @greenscreens-io 

Thank you for your detailed description.

You have definitely found the circular references there, which will need correcting but i feel the correct approach there would be to remove the internal pointers from the row to the table etc at the point it is destroyed rather than moving to `let`, which regardless of the version of babel will still not make it through transpilation.

These sorts of circular dependencies will have been a problem long before the advent of ES6 and while the let approach may resolve them in your instance, i would prefer to ensure that the underlying design flaw is fixed, rather than just patching over the references with a `let`

Your post today makes me think there may be something more going on with the decompression browser side. Tabulator is only responsible for handling the javascript objects that are passed to it, so i would suggest that you do a comparison between the objects from your decompressed output and the objects from your standard objects to see what the differences are.

It is likely that the decompression function is maintaing references to the objects passed into Tabulator which may be leading to the rows objects being maintained after deletion.

You many need to deep clone the data from the decompression library before passing it into tabulator to ensure it is fully isolated.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
The 5.0 release has had a full overhaul of the loader and event management systems so this should no longer be an issue in the 5.0 releases

Cheers

Oli :)
