### ISSUE TITLE
Scrolling glitch with nested tables

### ISSUE THREAD

**Issue by leoj-cs** [olifolkerd/tabulator#2309]
v4.4.1
When attempting to create nested tables using the exact code in the demo, the scrolling breaks: https://jsfiddle.net/vudytg62/1/
The table seems to glitch and erases data and doesn't scroll past the first nested table.
 
The same behaviour occurs on the demo page.

**Comment by takuy** [comment]
Hi @leoj-cs I had a similar issue, but my situation was a bit more complicated - please see for how it was resolved: https://github.com/olifolkerd/tabulator/issues/2074

**Comment by leoj-cs** [comment]
Hi @takuy .
The difference, is that there is no changing the data in the table. I tried calling table.redraw(true) after the data was loaded but the problem still persists.

**Comment by olifolkerd** [comment]
@leoj-cs 

Your JS Fiddle seems to be working correctly for me, what are you expecting to happen?

Cheers

Oli :)

**Comment by leoj-cs** [comment]
Hi
I have provided a link of a screen recording to demonstrate the issues. I am constantly trying to scroll in the table, and as can be seen, it jumps around from one end to another and sometimes the entire table freezes: https://www.dropbox.com/s/sgsacma9cdkqgbu/Screen%20Recording%202019-10-01%20at%2011.37.03.mov?dl=0

**Comment by olifolkerd** [comment]
Hey @leoj-cs 

That is because you are radically altering the row size when the nested table is opened, well beyond the height of the table so the virtual DOM is struggling to adapt.

I would suggest two possible workarounds that may help.

you could try increasing the virtual dom buffer to make space for your much larger rows, you should set it to be 3 time bigger than your biggest nested table:
```js
var table = new Tabulator("#example-table", {
    virtualDomBuffer:300, //set virtual DOM buffer to 300px
});
```
You could also try calling the ***redraw*** function on the table when the table is expanded, this may help.

I hope that helps

Oli :)

**Comment by leoj-cs** [comment]
Calling redraw did not work, but setting the virtualDomBuffer did. Thanks!

**Comment by olifolkerd** [comment]
@tentus Just a quick note, this is a great example of what the virtualDomBuffer is for :)

**Comment by vishMeta121** [comment]
How we set virtualDomBuffer size to dynamically as my nested table size could be anything according to data?
