### ISSUE TITLE
New Persistence: true  - data is not defined

### ISSUE THREAD

**Issue by hfhbd** [olifolkerd/tabulator#2499]
**Describe the bug**
The new persistence module is not working. Enabling this mode prevents the table from loading/rendering.

**Tabulator Info**
- Which version of Tabulator are you using?
4.5.0

**Working Example**
https://jsfiddle.net/14hmfx59/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. See example and open console

**Expected behavior**
A rendered table

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Browser: Edge
 - Version: 17 and new Beta 79

Stacktrace:

VM18 tabulator.min.js:11 Uncaught ReferenceError: data is not defined
    at P.cookie [as readFunc] (VM18 tabulator.min.js:11)
    at P.retreiveData (VM18 tabulator.min.js:10)
    at P.initialize (VM18 tabulator.min.js:10)
    at t.u._buildElement (VM18 tabulator.min.js:4)
    at t.u._create (VM18 tabulator.min.js:4)
    at new t (VM18 tabulator.min.js:4)
    at window.onload ((index):35)

**Comment by djollieb** [comment]
I'm also getting this error after I updated to version 4.5 today. It was working before the update.

**Comment by olifolkerd** [comment]
@djollieb 

If your issue isnt related to the persistence module, please create a new issue using the bug template, and create a JS fiddle that replicates the problem.

Im afraid without a simplified JS Fiddle that replicates the issue it will be impossible to help you.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @hfhbd  and @djollieb 

Bot of those issue were valid, i have just released the 4.5.1 branch which should hopefully resolve your problems,

Thanks for getting in touch.

Cheers

Oli :)

**Comment by pressec** [comment]
Hi @olifolkerd ,
Took @hfhbd  fiddle and updated it to use latest version (from CDN), but still the same error "data is not defined" shows:
https://jsfiddle.net/pressec/do2fLnj1/

Thanks for this great tool!
Dani

**Comment by pressec** [comment]
Sorry, the link I posted is gone. This is the right one: https://jsfiddle.net/pressec/ugevsban/

It works on Chrome but fails on Firefox:
```

ReferenceError: data is not definedtabulator.min.js:11:1343
    cookie https://unpkg.com/tabulator-tables@4.5.1/dist/js/tabulator.min.js:11
    retreiveData https://unpkg.com/tabulator-tables@4.5.1/dist/js/tabulator.min.js:10
    initialize https://unpkg.com/tabulator-tables@4.5.1/dist/js/tabulator.min.js:10
    _buildElement https://unpkg.com/tabulator-tables@4.5.1/dist/js/tabulator.min.js:4
    _create https://unpkg.com/tabulator-tables@4.5.1/dist/js/tabulator.min.js:4
    t https://unpkg.com/tabulator-tables@4.5.1/dist/js/tabulator.min.js:4
    onload https://fiddle.jshell.net/pressec/ugevsban/show/:35
```

**Comment by olifolkerd** [comment]
@pressec That is working just fine for me on chrome and firefox

**Comment by pressec** [comment]
@olifolkerd just saw Firefox was blocking access to local storage/cookie as I had third party cookies disabled. Thanks for looking into it. Cheers
