### ISSUE TITLE
Horizontal Scroll Lost On Header Filter Or Sort

### ISSUE THREAD

**Issue by ddelano34** [olifolkerd/tabulator#3450]
I'll start by saying this is an awesome project and appreciate all of the work that has gone into it.

**Describe the bug**
When filtering or sorting a table that has enough columns and data to horizontal scroll, if you scroll to the far right column and sort/filter it will return the horizontal scroll position back to the far left (0) position.

**Tabulator Info**
5.0.7

**Working Example**
https://codepen.io/dan-delano/pen/NWvXpGQ

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Scroll table to far right
2. Type in the header filter to filter the rows
3. Table should scroll back to left position
alternate:
1. Scroll table to far right
2. Click on the sort for the last column
3. Table should scroll back to left position

**Expected behavior**
Previous versions would maintain the horizontal scroll position when filtering and sorting a column.

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Browser: chrome
 - Version: 95.0.4638.69

**Additional context**
In the file modules/Filter/Filter.js there is a TODO on line ~560 that says 'Persist left position of row manager'. 
I tried to pass renderInPosition: true to refreshData when it is called in the Filter and Sort module. This sort of worked and kept the horizontal scroll position, but the empty table placeholder acted weird in that case.

**Comment by walkermatt** [comment]
I'm currently evaluating Tabulator and have also experience this issue.

**Comment by AndrewHutcheson** [comment]
I am also having this issue, on filter the table horizontal scroll goes back to the beginning.

**Comment by Tiuipuv** [comment]
I also have this issue.

**Comment by olifolkerd** [comment]
Hey All

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Comment by germanfr** [comment]
Hi all, 

The issue is still present when using remote filtering. [This commit](5cbb9b95b80ad78089c7269aec247d92bda59f71) only fixes the issue for local data.

```diff
 refreshFilter(){
 	if(this.tableInitialized){
 		if(this.table.options.filterMode === "remote"){
 			this.reloadData();
 		}else{
-			this.refreshData();
+			this.refreshData(true); // <---- The fix never executes if filterMode === 'remote'
 		}
 	}
 
  	//TODO - Persist left position of row manager
 	// left = this.scrollLeft;
 	// this.scrollHorizontal(left);
 }
```

**Comment by germanfr** [comment]
I have solved it by applying this change in `src/js/modules/Page/Page.js`, but I don't know if that breaks anything else.

```diff
 _parseRemoteData(data){
     var left, data, margin;
     
     if(typeof data.last_page === "undefined"){
         console.warn("Remote Pagination Error - Server response missing '" + (this.options("dataReceiveParams").last_page || "last_page") + "' property");
     }
     
     if(data.data){
         this.max = parseInt(data.last_page) || 1;
 
         this.remoteRowCountEstimate = typeof data.last_row !== "undefined" ? data.last_row : (data.last_page * this.size - (this.page == data.last_page ? (this.size - data.data.length) : 0));
         
         if(this.progressiveLoad){
             switch(this.mode){
                 case "progressive_load":
                 
                 if(this.page == 1){
                     this.table.rowManager.setData(data.data, false, this.page == 1)
                 }else{
                     this.table.rowManager.addRows(data.data);
                 }
                 
                 if(this.page < this.max){
                     setTimeout(() => {
                         this.nextPage();
                     }, this.table.options.progressiveLoadDelay);
                 }
                 break;
                 
                 case "progressive_scroll":
                 data = this.page === 1 ? data.data : this.table.rowManager.getData().concat(data.data);
                 
-                this.table.rowManager.setData(data, this.page !== 1, this.page == 1);
+                this.table.rowManager.setData(data, true, this.page == 1);
                 
                 margin = this.table.options.progressiveLoadScrollMargin || (this.table.rowManager.element.clientHeight * 2);
                 
                 if(this.table.rowManager.element.scrollHeight <= (this.table.rowManager.element.clientHeight + margin)){
                     setTimeout(() => {
                         this.nextPage();
                     });
                 }
                 break;
             }
             
             return false;
         }else{
```

**Comment by diverdm** [comment]
Tabulator v.5.4.4 from unpkg.com CDN. The problem is still actual.

**Comment by Kelvinyhl** [comment]
still the same, anyone have any solution?

**Comment by 0xAliRaza** [comment]
I'm using  v5.5.0 and the problem persists.

**Comment by dmorgan** [comment]
Would you all ask Oli to get me off this list. Nothing else seems to work.

UNSUBSCRIBE !!!!!!!!!!!!

========================================================

**Comment by x11joe** [comment]
I can confirm the issue with remote is still present.  If I can help Oli in anyway just let me know :), I'm more then happy to help code assist with your project :).

**Comment by sf-csmith** [comment]
Still having this issue in 5.5. I stepped through the code and the table is literally being regenerated so it makes sense we'd lose the scroll.

**Comment by 0xAliRaza** [comment]
Here's a workaround guys. You can save the field of the column in your state and then scroll to it whenever you want.
From my vue component:
```vue
  tabulator.value.scrollToColumn(col.field);
```

**Comment by deepakup94** [comment]
Horizontal scroll reset itself to left in remote pagination in 6.2 version as well. It resets with filter/sort/ page size change/page change. @olifolkerd

**Comment by Anton-Plagemann** [comment]
Hey all,
I stumbled across this issue and decided to reopen it with #4494.
I've identified some small changes (described in detail [here](https://github.com/olifolkerd/tabulator/issues/4494#issuecomment-2102214506) that might fix the issues (at least fixes them for me).

For now I'm using [patch-package](https://www.npmjs.com/package/patch-package) with the following file (including these small changes) to have it working until there's an official fix. Feel free to use it too (just install `patch-package` as described and put the file into a new `/patches` directory) 😊

NOTE: This fix might be only valid for ESM-Usage (no `require()`, only `import`).
[tabulator-tables+6.2.1.patch](https://github.com/olifolkerd/tabulator/files/15260155/tabulator-tables%2B6.2.1.patch)
