### ISSUE TITLE
responsiveLayout: 'collapse' causes page to hang since v.5 

### ISSUE THREAD

**Issue by antman3351** [olifolkerd/tabulator#3464]
**Describe the bug**
Resizing the table with options  `layout: 'fitColumns'` and `responsiveLayout: 'collapse'` causes the page to hang. Version 4.9 works fine.

**Tabulator Info**
5.0.7

**Working Example**
https://jsfiddle.net/yxams4pk/10/

**To Reproduce**
Quickly resize the window a few times

**Screenshots**
Here's a screen of the js fiddle. I ran the same code against v. 4.9 and 5.0 to show the difference.
Note, it's not too bad in the example because the table is simple.
![Tabulator](https://user-images.githubusercontent.com/16060462/141118407-2b471aa3-ca65-456f-ba35-3af5602a924b.gif)

Here a screen of what happens with a table that has formatters. The page crashes
![Tabulator-prod](https://user-images.githubusercontent.com/16060462/141118609-a788c9d4-cf82-41d8-baaa-9e12cac50cdb.gif)

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Version 95.0.4638.69

**Additional context**
I really like Tabulator, Thanks for the effort it's much appreciated! 👍👍👍

**Comment by GreenX5** [comment]
I confirm the problem, any "responsiveLayout" value causes Chrome to freeze after changing columns several times. This issue was not present in versions 4.xx

**Comment by olifolkerd** [comment]
Hey @antman3351 

I have pushed a fix for this to the master branch and will include it in the next patch release.

Cheers

Oli :)

**Comment by AvishekPaul** [comment]
layout: 'fitColumns' causes page to freeze/hang when it is resized. This issue is not fixed yet. When I resize multiple times, the tab gets hang. like in this given screenshots. I am using version "tabulator-tables": "^5.5.0", still have this issue.
