### ISSUE TITLE
Uncaught Promise in Progressive Loading

### ISSUE THREAD

**Issue by grosscol** [olifolkerd/tabulator#3482]
**Describe the bug**
Using `progressiveLoad: "scroll"` an uncaught promise error gets thrown and the table stops loading after scrolling down a sufficient number of times.  After `.getPage()` reaches `.getPageMax()`, this appears to occur sometime during the next ajax request.

The top calls in the stack correspond to these lines in the codebase
- https://github.com/olifolkerd/tabulator/blob/cd094482af8792ae16931809e55b834020aa496a/src/js/modules/Page/Page.js#L613
- https://github.com/olifolkerd/tabulator/blob/cd094482af8792ae16931809e55b834020aa496a/src/js/modules/Page/Page.js#L201
- https://github.com/olifolkerd/tabulator/blob/c260bdfd08a68130c68b27d67f100db11932dc17/src/js/core/tools/InternalEventBus.js#L119

Observed callstack from console:
```
Uncaught (in promise) undefined tabulator_esm.js:14493
    nextPage tabulator_esm.js:14493
    scrollVertical tabulator_esm.js:14085
    scrollVertical self-hosted:1175
    _dispatch tabulator_esm.js:21807
    forEach self-hosted:205
    _dispatch tabulator_esm.js:21806
    _dispatch self-hosted:1175
    dispatch tabulator_esm.js:79
    initialize tabulator_esm.js:20130
    (Async: EventListener.handleEvent)
    initialize tabulator_esm.js:20110
    initialzeCoreSystems tabulator_esm.js:22642
    Tabulator tabulator_esm.js:22591
    TabulatorFull tabulator_esm.js:23424
```

The scrollVertical event can be observed to show the relevant pagination values:
```js
table.on("scrollVertical", function(top){
  console.log(`top: ${top}, page: ${this.getPage()}, pageMax: ${this.getPageMax()}`)                                                                                                     
})
```

**Tabulator Info**
tabulator-tables@5.0.7

**Working Example**
https://jsfiddle.net/grosscol/gcs0ronk/22/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Open devtools console
2. Run fiddle
3. Examine error in console

**Expected behavior**
Progressive loading stops when page max is reached without emitting errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Browser Mozilla Firefox 94.0

**Comment by plataux** [comment]
I just ran into this issue as well. It seems to always happen when the table option is set to `` progressiveLoad: "scroll"`` and the user is trying to scroll past the last page. Happens on Firefox and Chrome 

```
| nextPage | @ | Page.js:613
| scrollVertical | @ | Page.js:201
| (anonymous) | @ | InternalEventBus.js:119
| _dispatch | @ | InternalEventBus.js:118
| dispatch | @ | CoreFeature.js:78
| (anonymous) | @ | RowManager.js:114
```

**Comment by olifolkerd** [comment]
Hey All,

I have pushed a fix for this to the master branch and will include it in this evenings patch release.

Cheers

Oli ;)

**Comment by Ferrer-Jeremy** [comment]
Hey !

I ran into this bug. It seams to still be present in 5.0.10

**Comment by grosscol** [comment]
Updated the fiddle to use 5.0.10.  Looking at the console, the error still appears.
```
Page.js:611 Uncaught (in promise) undefined
```
I see five ajax preflight and fetches for 
 https://jsonplaceholder.typicode.com/photos?albumId=1
 https://jsonplaceholder.typicode.com/photos?albumId=2
 https://jsonplaceholder.typicode.com/photos?albumId=3
 https://jsonplaceholder.typicode.com/photos?albumId=4
 https://jsonplaceholder.typicode.com/photos?albumId=5

The example hacks in `last_page = 5` to the responses, so tabulator should think that is the last page.
It's not until after the last request that the error occurs.

**Comment by germanfr** [comment]
I'm experiencing the same issue with progressive scrolling on version 5.1.0. It happens when the table is taller than the list of rows (for example when filtering).

**Comment by olifolkerd** [comment]
Hey All,

This all seems to be working fine when i test it my end, is there any more info that anyone can provide that may help me narrow down onthis.

Cheers

Oli :)

**Comment by grosscol** [comment]
@olifolkerd I've updated the js fiddle to use tabulator-tables 5.1.0:  https://jsfiddle.net/grosscol/gcs0ronk/  It appears the issue is still demonstrable with the fiddle.

Using Firefox watching the console in the developer tools when you run the fiddle, the following error appears:

`Uncaught (in promise) undefined` [Page.js:701:18](https://unpkg.com/tabulator-tables@5.1.0/src/js/modules/Page/Page.js)

I've added some console logging to illustrate when the error occurs.  I see five ajax requests generated and then the error shows up when I run the fiddle.

**Comment by DarryStraits** [comment]
Hi Oli and All,

I can confirm too that with ajax loading set to scroll, when scroll height is <= clientHeight + margin (checked into _parseRemoteData function in case of "progressive_scroll" is active), which it can happen if the ajax call only returns 5 rows, for example (just one page of results), then nextPage is fired and throws an "Uncaught (in promise)". 

Once in nextPage function, it does this:

value: function nextPage() {
        if (this.page < this.max) {
          this.page++;
          this.trackChanges();
          return this.trigger();
        } else {
          if (!this.progressiveLoad) {
            console.warn("Pagination Error - Next page would be greater than maximum page of " + this.max + ":", this.max + 1);
          }
          return Promise.reject();    //////////////////////////////////// ----> Here is the Promise.reject uncaught!!!
        }

The point here is that, following the example of just 1 page of data returned by the Ajax call (page = 1 and max = 1, so this.page = this.max), it returns a Promise.reject that is uncaught if running in progressiveLoad mode, as far as I can see.

If the Ajax call returns more than one page (always talking about ajax scroll mode) everything is OK, but then if you filter the table and the result is just one page, the uncaught (in promise) is thrown again.

Tested with version 5.1.0 in Chrome and Firefox both latest versions (Windows 10). Sorry to not include a JSFiddle for this. I just wish it can help you somehow to find the error, as you are helping us all with your work, time and your awesome Tabulator. I love it. Thank you very, very much, Oli.

Here is the Firefox console trace of the exception from my localhost developing server, just in case:

Uncaught (in promise) undefined [tabulator.js:21929:26](http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js)
    nextPage http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:21929
    _parseRemoteData http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:22065
    (Asíncrono: setTimeout handler)
    _parseRemoteData http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:22064
    _parseRemoteData self-hosted:1178
    _chain http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:6951
    forEach self-hosted:208
    _chain http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:6950
    _chain self-hosted:1178
    chain http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:383
    load http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:6622
    (Asíncrono: promise callback)
    load http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:6617
    _loadInitialData http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:8191
    _create http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:8050
    Tabulator http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:7963
    (Asíncrono: setTimeout handler)
    Tabulator http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:7962
    construct self-hosted:2741
    _createSuperInternal http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:116
    TabulatorFull http://localhost/apiReminder/app/assets/pack/tabulator/v5.1.0/js/tabulator.js:25548

**Comment by olifolkerd** [comment]
Hey All,

When setup correctly the table works absolutely fine in my testing. 

The issue in the JS Fiddle example used at the start of this issue is that the table has no height, so it is continually trying to load data.

There is no point using progressive loading on a table that has no height, it will load all the data at once anyway and fill the screen. The whole point of progressive loading is to load silently in the background out of view of the visible part of the table

Cheers

Oli

**Comment by olifolkerd** [comment]
I have pushed an update to master to prevent the scroll pagination from attempting to load beyond the last page when it is initializing the data which is where i think this exception is originating.

I will include it in the 5.1.1 patch release.

Cheers

Oli :)

**Comment by DarryStraits** [comment]
Hey Oli,

I have just tried your update and I can confirm there is no exception thrown now. Bravo! 
Just for the record, all my progrerssive load tables have always a height defined, so the problem was not to check if(this.page < this.max) before launching nextPage on _parseRemoteData in progressive_scroll mode, as you corrected now. 

Thank you, Oli, for your pattience and efforts. :)

By the way, I have just invited you to a beer (or coffee or whatever) by PayPal. Cheers! ;)
Darry
