### ISSUE TITLE
Column calculation totals mis-alignment occurs on grouped table 

### ISSUE THREAD

**Issue by hdbonnett** [olifolkerd/tabulator#3518]
**Issue Description**
I have created a table grouped by one field (State) and one to many rows of detail below. There are column groups in use as well with 2 columns per group. Column calculations (sum) are being generated on most quantity fields. For the top 3 or 4 groups the alignment of the calculation totals is as expected, but in the last several groups the totals are shifted two columns right. The data "snaps back" to the right position if you resize one of the columns but will be in the wrong spot on a refresh.

**Tabulator version**
@latest via CDN (5.0.8 today) with Tabulator-Bootstrap3 theme. 

**Working Example**
Issue can be reproduced here: https://jsfiddle.net/hdb_ip/hqa2m4e9/15/

**To Reproduce**
Open https://jsfiddle.net/hdb_ip/hqa2m4e9/15/
and scroll down. The column top calculated values are in correct place (just above detail) for ACT, NSW & QLD. 
When you get to SA, the calculated values shift 2 columns over for all remaining groups.
If you resize the one of the cells, the data will appear where expected.

**Expected behavior**
The column calculations should be in the same location, above the detail data, for all groups.
**Screenshots**
![image](https://user-images.githubusercontent.com/19419731/147439557-a8b01db4-5a97-45fd-837b-e077cb83162e.png)

Correct:
![image](https://user-images.githubusercontent.com/19419731/147439591-058a406a-c036-41e7-8787-55e560a3780d.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Firefox 95.0.2 & Chrome 96.0.4664.110 (tested on both)

**Smartphone (please complete the following information):**
Not tested

**Additional context**
I'm also using Jquery 3.6.0 & jquery.sparklines 2.0.2 on the full version but I have reproduced this with them removed. I have also tested w/o Responsive layout, using only base Tabulator.min.css and with FitColumns but the problem happens for all combinations.
You can also see "live version" here: https://tgbc.info-prime.dev/api/test.html if needed.

**Comment by olifolkerd** [comment]
Hey @hdbonnett 

I have pushed a  fix for this to the master branch and will include it in the next patch release.

I do have a couple of notes about your Issue, first of these is a table setup issue, you have a frozen column in your table and responsive collapse enabled. There is no point in having both as the frozen column will never be used because the table will always collapse away columns first.

The second issue is to do with the example code. While the example you provided does demonstrate the issue, it contained a huge amount of additional code that wasnt needed to demonstrate the issue (which was actually just a frozen column with grouped data.= and column calcs enabled.  When reporting bugs it is best practice to use a [Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) to make the actual issue as clear as possible.

Cheers

Oli :)

**Comment by hdbonnett** [comment]
Thanks @olifolkerd  - this is my first project with Tabulator (jqGrid in the past) so I'm still getting my head around some of the ways it works and hadn't realised that the frozen column would conflict with the responsive layout. I included a good sized chunk of code (minus bits I had confirmed weren't involved) since I wasn't sure what could be causing the issue. The same holds for the amount of test data, the issue wasn't occurring with a smaller data set.
Cheers,
Dave
