### ISSUE TITLE
bootstrap 5 theme creates horizontal scrollbars with layout:"fitColumns"

### ISSUE THREAD

**Issue by dtocci** [olifolkerd/tabulator#3700]
Horizontal scrollbars appear on all tables with layout:"fitColumns" in the BootStrap 5 theme.

https://jsfiddle.net/1qpodhcg/

The bug is caused by the CSS rule for:
.tabulator .tabulator-col-resize-handle 

Tabulator 5.2

**Comment by olifolkerd** [comment]
Hey @dtocci 

Thanks for the info. i have just released the 5.2.1 release that should resolve this issue.

Cheers

Oli :)

**Comment by juanvalag2019** [comment]
Hi,

Still present with Bootstrap 5 theme and Tabulator 5.2.4
