### ISSUE TITLE
Uncaught TypeError on header filter blur

### ISSUE THREAD

**Issue by bornova** [olifolkerd/tabulator#3707]
**Describe the bug**
When switching from one header filter input (type 'list' with autocomplete) to another, after going back and forth a few times, I get the following error in console:

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Edit._resolveValue (<local-path>\node_modules\tabulator-tables\dist\js\tabulator.js:13475:48)
    at Popup.hide (<local-path>\node_modules\tabulator-tables\dist\js\tabulator.js:7443:18)
    at Edit._inputBlur (<local-path>\node_modules\tabulator-tables\dist\js\tabulator.js:12691:22)
_resolveValue @ <local-path>\node_modules\tabulator-tables\dist\js\tabulator.js:13475
hide @ <local-path>\node_modules\tabulator-tables\dist\js\tabulator.js:7443
_inputBlur @ <local-path>\node_modules\tabulator-tables\dist\js\tabulator.js:12691
```

On a side note, I also noticed the filter dropdown is now opened to the top if the table is positioned lower in the page and there is enough room for the dropdown container.  Not sure if this is intentional but opening the dropdown to the bottom as default would be better IMHO.

**Tabulator Info**
- Which version of Tabulator are you using? 5.2.1

**Working Example**

https://jsfiddle.net/izmirli/y1b54tpq/2/

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to https://jsfiddle.net/izmirli/y1b54tpq/2/
2. Click inside Name header filter input
3. Without selecting anything, now click inside Gender header filter input
4. Do this back and forth a few times
5. See error (jsfiddle only shows `"Script error."` in it's console but more verbose error is shown in my application as mentioned above)

**Comment by olifolkerd** [comment]
Thanks for the heads-up. I'm putting together a patch release this weekend to address and 5.2 launch issues and will include a fix for this bug there.

The drop-down menus should only appear above editors input if there is not enough space below the header. If you believe you have managed to trigger this behaviour when there is sufficient space underneath, would you mind rasing a separate issue with a fiddle to demonstrate so that it can be tracked separately.

Cheers

Oli :)

**Comment by bornova** [comment]
Thanks Oli!  I will open a separate issue for the input list dropdown.

**Comment by olifolkerd** [comment]
Hey @bornova 

I have pushed a fix for this to the master branch and will include it in a patch release later today.

Cheers

Oli :)

**Comment by bornova** [comment]
Hi Oli,
FYI, this bug still exists in v5.2.2

https://jsfiddle.net/izmirli/rqxc40tv/

**Comment by bornova** [comment]
Hi @olifolkerd,
FYI, this bug still exists in v5.2.3

https://jsfiddle.net/izmirli/rqxc40tv/3/

**Comment by olifolkerd** [comment]
Hey @bornova  

Thanks for the info, but if it was fixed on that release it would have been included in the release notes.

There was a PR with a fix last week that i have just merged into master so it will be included in the next patch release. You don't need to prompt me on each release.

Cheers

Oli :)

**Comment by bornova** [comment]
Hi Oli,
Based on your commend below and since the issue was closed before the fix, I thought maybe it was overlooked.  I will pay better attention to the release notes from now on.  I would suggest keeping the issues open until the fix is released though, so we know it is stilll being worked on :)

Thank you!

> Hey @bornova
> 
> I have pushed a fix for this to the master branch and will include it in a patch release later today.
> 
> Cheers
> 
> Oli :)
