### ISSUE TITLE
Tooltip is visible after table is destroyed

### ISSUE THREAD

**Issue by etomanon** [olifolkerd/tabulator#3742]
**Describe the bug**
Tooltip is visible after table is destroyed or when user is redirected to another URL on row click.

**Tabulator Info**
5.2.4

**Working Example**
[JS Fiddle](https://jsfiddle.net/3mh0y65b/7/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Hover over cell for a while
2. Move a little bit but be still over the cell
3. Click before the tooltip appears
4. Table is destroyed and tooltip appears after that. You can get rid of it only when you click again.

**Expected behavior**
Remove tooltips when table is destroyed

**Screenshots**
![Tabulator - JSFiddle - Code Playground](https://user-images.githubusercontent.com/17390813/167661468-bbcfba70-28b4-4a50-9de5-782218fc8d40.gif)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome

**Comment by olifolkerd** [comment]
Hey @etomanon 

Thanks for the example there, that is great for the table being destroyed but dosnt demonstrate how your are redirecting the user to a new page, this is a vauge description and could be handled in numerous ways.

Could you look at updating your example to include this as well, maybe by using cellClick on two columns, one that deletes the table, one that triggers your linking?

Cheers

Oli :)

**Comment by etomanon** [comment]
@olifolkerd I think if we can remove the tooltips after the destroy event automatically then it will solve the linking problem too because the table is destroyed after redirection.
I use tabulator in React and I do not think I can simulate the URL change in JS Fiddle.

**Comment by olifolkerd** [comment]
Hey @etomanon 

I have just pushed an update to master to hide popups when the table is destroyed.

This will be included in this weekends patch release.

Cheers

Oli :)

**Comment by etomanon** [comment]
@olifolkerd the bug is still present in 5.2.6: https://jsfiddle.net/rzs90kg2/1/
Do the same thing as in the gif and the tooltip is still there after the table is destroyed :(

Maybe the tooltip is created after the table is completely destroyed so the fix with event listener does not work?

**Comment by olifolkerd** [comment]
This is happening because the timeout for the tooltip is engaged before the destroy is triggered which then shows the popup after the table has been destroyed. So Tabulator is correctly clearing popups at the point of destruction, it is just not preventing ones on a timeout from being created in the first place.

I will add a fix for that in the next patch release.

Cheers

Oli :)

**Comment by skirianov** [comment]
@olifolkerd is it open for contribution? Seems like something I can work on ;)

**Comment by olifolkerd** [comment]
@skirianov I have a patch release going out Sunday eve. If you are up for getting it in for the than go for it, otherwise I will get it in myself before the release :)

**Comment by olifolkerd** [comment]
Hey all,

I have pushed a fix for this to the master branch and will include it in sundays patch release.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @etomanon 

Do you have an example that replicates this, it is working fine in my setup?

Cheers

Oli :)

**Comment by etomanon** [comment]
@olifolkerd here it uses the v5.2.7. It is harder to replicate but it happens often enough.
https://jsfiddle.net/2w7ty0b8/
![Untitled_ Jun 8, 2022 10_28 AM](https://user-images.githubusercontent.com/17390813/172570687-78046760-2951-4d24-97fb-099c144f9d80.gif)
