### ISSUE TITLE
bug on horizontal scroll in RTL  

### ISSUE THREAD

**Issue by majidh1** [olifolkerd/tabulator#3818]
**Describe the bug**
RTL Bug: 
scroll not working on bottomCalc
horizontal scroll end table break 

**Tabulator Info**
5.2

**Working Example**
https://jsfiddle.net/cLr4ebto/1/

**To Reproduce**
1. Scroll left
2. See bug on bottom
3. scroll end
4. See table break bug

**Screenshots**
![Capture](https://user-images.githubusercontent.com/43379900/174948470-b065319b-24d0-47b7-8693-0cdf41590f3b.PNG)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: chrome 90+

**Comment by olifolkerd** [comment]
Hey @majidh1 

Thanks for the headsup, i have pushed a fix for this to the 5.3 branch that will be released in a couple of weeks.

Cheers

Oli :)

**Comment by majidh1** [comment]
Hey @olifolkerd 
Thanks for the response, I checked that commit.. changes did not resolve both bug

**Comment by olifolkerd** [comment]
I have run your demo on my local machine and it does resolve both issues for me.

Have you pulled the whole branch down rather than the one commit?

**Comment by majidh1** [comment]
The problem occurs when vertical scrolling is displayed in the body, 
it misalignment column by scrolling to the end of table 
and also table BottomCalc onScroll not Working
see this sample: (css is last commit)
https://jsfiddle.net/majidh1/r8qk29od/9/

**Comment by olifolkerd** [comment]
Hey @majidh1 

It is all working correctly on my version of the 5.3 branch on my local machine, i haven't regenerated all of the dist files which is probably while you are running into issues, i only do this when i release the version. This wasnt just a CSS update, there was changes to the JS needed to.

Please try the 5.3 release when it comes out in a week or so and then let me know if you are still hving issues.

Cheers

Oli :)

**Comment by majidh1** [comment]
Hey @olifolkerd

i recheck bugs on the new version version (5.3) scrolling on the footer works correctly and there is no problem, many thanks 👍 🥇
But still the header columns are misaligned when scrolling ends. 🙁

![image](https://user-images.githubusercontent.com/43379900/178192245-33adddd6-cd4a-4615-81b8-3b30fceefcc1.png)

**Comment by olifolkerd** [comment]
Please create an updated js fiddle, I am unable to replicate that behavior
on my computer

Cheers

Oli

**Comment by majidh1** [comment]
https://jsfiddle.net/majidh1/tgahe7uk/2/

https://user-images.githubusercontent.com/43379900/178207244-b5d59f79-b12b-4b66-a8c1-0c65cfa75c85.mp4
