### ISSUE TITLE
5.2.7 editor="List" issue on Android phone

### ISSUE THREAD

**Issue by tsiporn** [olifolkerd/tabulator#3828]
**Information**
Tabular: 5.2.7
Phone: Android 10

**Fiddle**: https://jsfiddle.net/tsiporn/zL3vcfxp/28/
see column Gender in Fiddle

**Problem description**
Working on 5.2.7 with editor="list" feature.  It seems okay on laptop (Windows), but it's not okay on mobile phone (Android).  When tab on the cell (with the list feature), Android keyboard appear immediately and the focus on the cell lost.  This make impossible to edit the cell.

**Comment by olifolkerd** [comment]
Hey @tsiporn 

Thanks for the info there.

Looks like the keyboard was causing the screen to resize which then immediately cancelled the editor. I have pushed a fix for this to the 5.3 branch that will be released in a couple of weeks.

Cheers

Oli :)

**Comment by jaguarxii** [comment]
Hi, I still have this issue is there anything to update besides the version of the ".js" file?

I have custom CSS styles applied to the table.

**Comment by tsiporn** [comment]
Hi @jaguarxii,

It works to me but a bit tricky.  Have to select the target row by tapping any other columns (not the column with the list), then tap on the column with the list.

**Comment by olifolkerd** [comment]
Hey @jaguarxii 

Confirmed, it was only partially fixed, i will include a fix for it in todays patch release.

Cheers

Oli :)
