### ISSUE TITLE
Datatree indentation

### ISSUE THREAD

**Issue by jaguarxii** [olifolkerd/tabulator#4213]
**Describe the bug**
Weird behavour when the dataTreeBranchElement option is set to "false".

**Tabulator Info**
- 5.5

**Working Example**
[tabulator tree](https://codepen.io/jaguarito/pen/BaGBPqV)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. When the dataTreeBranchElement is set to false, the indentation is not working properly.

**Screenshots**
![image](https://github.com/olifolkerd/tabulator/assets/8013436/c5337b3b-8182-4982-b6f2-6855f28ad80e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Waterfox latext, Chrome latest, Edge latest

**Smartphone (please complete the following information):**
 - did not tested

**Comment by lukecotter** [comment]
@jaguarxii 
I have also hit this recently.
As a workaround `dataTreeBranchElement: '<span></span>',` works.

**Comment by mdmangus** [comment]
I'm using the default indentation markers unlike the original poster wanting to hide them.  Even with them turned on I'm seeing an alignment mismatch of the angle brackets.

 I brought the code down to compare against 5.5.0 against 5.4.4.  I see no indentation issues until I bring in the changes from file:
VirtualDomVertical.js

Here is what I see where the brackets don't align up

![TreeDataIndentationIssues](https://github.com/olifolkerd/tabulator/assets/1176378/00a53ef4-7961-4994-8602-f1daf777a6c7)

**Comment by lukecotter** [comment]
@mdmangus You are right this is due to the changes in the VirtualDomVertical.js.

@olifolkerd 
Since the row is now not added to the dom when layoutRow is called in the [data tree](https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/DataTree/DataTree.js#L247) the branch element does not have an offsetWidth.
I will try to come up with a fix that does not negated the performance improvements, possible adding the branch element to the table just once at the beginning to determine a width?

**Comment by olifolkerd** [comment]
Hey @jaguarxii 

Thanks for the info,

I have pushed a fix for this to the master branch and will include it in todays patch release.

Cheers

Oli :)

**Comment by mdmangus** [comment]
> https://codepen.io/mdmangus/pen/MWzmRox

@lukecotter @olifolkerd 

Just an FYI.

I tried upgrading from 5.4.4 to 5.5.2 just now and still see the alignment issue.  I updated above codepen to 5.5.2 which still shows the issue that I referred to above.
