### ISSUE TITLE
Column alignment issue after sorting

### ISSUE THREAD

**Issue by Amrit901** [olifolkerd/tabulator#708]
Hi team,

I'd like to thank you for the great work you have done. Coming to the issue observed, 
I have a large table which is having horizontal scroll and paging.
The column alignment is broken once you sort the table by any column. Though after scrolling it gets fixed. Is there any suggestion to fix it? Same issue observed in http://tabulator.info/
![column](https://user-images.githubusercontent.com/33649735/32766258-2688b226-c934-11e7-98fb-5ea059f8818b.PNG)

**Comment by olifolkerd** [comment]
hey @Amrit901,

that is definitely a bug i will add a fix to the next patch release. Thanks for letting me know.

Cheers

Oli

**Comment by olifolkerd** [comment]
hey,

I have just pushed a fix for this to the master branch, it will be included in this evenings patch release

Cheers

Oli

**Comment by Cerebres** [comment]
Is it possible that I am still expriencing this issue? I am using 2 frozen columns, load, sort and filter my data via ajax and am also using remote pagination.

**Comment by olifolkerd** [comment]
if you just sort the data instead of filtering is the issue still there?

**Comment by Cerebres** [comment]
Yes, it happens both with filtering and sorting.

**Comment by Cerebres** [comment]
Hi,
Do you have any news on this? Can you reproduce the issue?
Thanks for the support!

**Comment by olifolkerd** [comment]
Hey @Cerebres 

I cant seem to replicated the issue, but iam spending the next couple of weekends working on version 3.4 so will dig deeper into the issue then.

Cheers

Oli

**Comment by Cerebres** [comment]
Hi @olifolkerd ,

Did you manage to replicate the issue? I am still facing the problem, but it can be something that I am doing wrong ofcourse.

Many thanks

**Comment by olifolkerd** [comment]
Hey @Cerebres ,

I have been struggling to reproduce it, but i think i might just have found a reproducible set of steps:
- resize screen so table needs horizontal scroll bar
- scroll to the far right
- change to page 2
- sort last column
- ALIGNMENT ERROR

would you mind confirming that this is what you are seeing? i will have a look into the cause of that this week.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @Cerebres,

I have gotten to the bottom of the issue, there was a problem with the "left" scroll value being incorrectly reset in classic render mode.

I have just released patch release 3.4.5 which includes a fix for this.

Let me know if that has fixed it for you.

Cheers

Oli :)

**Comment by Cerebres** [comment]
@olifolkerd ,

Unfortunatly this did not fix my issue. I am still experiencing the left scroll problem in ajax mode.

I also noticed in the newest version that div.tabulator-tableHolder height is too large, it resizes to fit the data instead of playing nice and resize to fit to my 100% height request.

I am very sorry to be such a pain,
Cerebres

**Comment by olifolkerd** [comment]
Hi @Cerebres 

Sorry to hear that,

It has fixed the issue on the tabulator.info site.

You shouldn't be making any styling changes to the ***tabulator-tableHolder*** class, that is setup as it needs to be for tabulator to function correctly. making changes to this class could cause Tabulator to malfunction. What are you trying to achieve by changing this, I would be happy to recommend the correct course of action.

Without an example table constructor and a reproducible step by step guide of how to reproduce your issue, i will be unable to fix it.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @Amrit901 

are you using version 3.5.3?

Cheers

Oli :)

**Comment by kiran-peddikuppa** [comment]
https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.5.1/js/tabulator.js

I tried using Tabulator theme and Semantic theme...I have the same issue

I justed tested on 3.5.3 and it looks like the same issue

![image](https://user-images.githubusercontent.com/7722043/42498304-6f767cfe-8449-11e8-866c-9a0edaecda90.png)

**Comment by ryhill** [comment]
Has this issue been fixed by any chance?? Sorry for the late response.. I am wondering if anyone has come across a solution for this 

Thanks

KIRAN

**Comment by olifolkerd** [comment]
Hey @ryhill 

Have you tried version 4.0 yet?

Cheers

Oli
