### ISSUE TITLE
BUG in selectedrows.

### ISSUE THREAD

**Issue by Rodbjartson** [olifolkerd/tabulator#830]
I have a table of one row.
I seledt the row and delete it. I add a new row, now I have apparently 2 selected rows according to 
`$(tablename).tabulator("getSelectedRows");`

seems like the function does not decrement the number of selectedrows when a row is deleted.

To reproduce the error:
-Select a row in your table
-Delete the selected row
-Select a new row
-Call getselectedrows function and print the length of the returned array

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

Looks like you have found an issue there, the row does not deselect itself before deletion, i will add this functionality in for the next release.

Cheers

Oli

**Comment by olifolkerd** [comment]
Hey @Rodbjartson 

You will be happy to hear i have just pushed a fix for this to the 3.4 branch, rows are now deselected when deleted.

This will be included in the 3.4 release in a couple of weeks time.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Tabulator version 3.4 has now been officially release!

You can find details of the new release in the [News Section](http://tabulator.info/news)

Full documentation of all the new features can be found [Here](http://tabulator.info/docs/3.4)

Cheers

Oli :)

**Comment by Rodbjartson** [comment]
@olifolkerd I am still experiencing this error, even though I have updated to 3.5!!
