### ISSUE TITLE
Misalignment of topCalc

### ISSUE THREAD

**Issue by MusinAmir** [olifolkerd/tabulator#992]
Hi again.
Misalignment of columns when using topCalc
![image](https://user-images.githubusercontent.com/14330661/37952313-c388fbe8-31b8-11e8-8e86-20dfaf608669.png)
Also after scrolling appears empty element, its hidden column "pg_name" considering the browser
![image](https://user-images.githubusercontent.com/14330661/37952527-78b112a8-31b9-11e8-8a2f-044ec1563f69.png)

``` javascript
        groupClosedShowCalcs:true,
        columns:[ //Define Table Columns
            {title: 'Группа проектов', field:'pg_name', headerSort:false, frozen:true},
            {title: 'pe_id', field:'pe_id', visible: false},
            {title: 'user_id', field:'user_id', visible:false},
            {title: 'Сотрудник', field: 'user', width: 120, visible:false},
            {title: 'pg_ids', field:'pg_id', visible: false},
            {title: 'Январь', field:'1', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Февраль', field:'2', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Март', field:'3', width:100,  editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Апрель', field:'4', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Май', field:'5', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Июнь', field:'6', width:100,editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Июль', field:'7', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Август', field:'8', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Сентябрь', field:'9', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Октябрь', field:'10', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Ноябрь', field:'11', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Декабрь', field:'12', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Всего', field:'total', width:100, headerSort: false, topCalc:"sum"}
        ],  

        groupBy:"user"
```
Thank you in advance!

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

Which version of Tabulator are you using? that issue should have been fixed in 3.5.5.

Cheers

Oli :)

**Comment by MusinAmir** [comment]
I'm using 3.4.6. I'll try 3.5.5

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

Sorry, my bad, i mean 3.4.5.

Could you post the whole of your Table constructor along with step by step instructions to replicate the error.

Cheers

Oli :)

**Comment by MusinAmir** [comment]
``` javascript
    $("#tabulator-example").tabulator({
        height: 500, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
        layout:"fitColumns", //fit columns to width of table (optional)
        history:true,
        autoResize:false,
        resizableColumns:false,
        resizableRows: false,
        groupClosedShowCalcs:true,
        columns:[ //Define Table Columns
            {title: 'Группа проектов', field:'pg_name', headerSort:false, frozen:true},
            {title: 'pe_id', field:'pe_id', visible: false},
            {title: 'user_id', field:'user_id', visible:false},
            {title: 'Сотрудник', field: 'user', width: 120, visible:false},
            {title: 'pg_ids', field:'pg_id', visible: false},
            {title: 'Январь', field:'1', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Февраль', field:'2', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Март', field:'3', width:100,  editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Апрель', field:'4', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Май', field:'5', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Июнь', field:'6', width:100,editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Июль', field:'7', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Август', field:'8', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Сентябрь', field:'9', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Октябрь', field:'10', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Ноябрь', field:'11', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Декабрь', field:'12', width:100, editor:true, validator:"min:0", headerSort:false, topCalc:"sum"},
            {title: 'Всего', field:'total', width:100, headerSort: false, topCalc:"sum"}
        ],  

        groupBy:"user",

        dataLoaded:function(data){ //freeze first row on data load
            var firstRow = $("#tabulator-example").tabulator("getRows")[0];
  
            if(firstRow){
                firstRow.freeze();
            }
         },
        cellEdited:function(cell){
            var row = cell.getRow();
            var hours = cell.getValue();
            var data = row.getData();
            var pg_id = data.pg_id;
            var year = "2018";
            var column = cell.getColumn();
            var month = column.getField();
            var ids = data.pe_ids
            var id = ids[month]
            var user_id = data.user_id;
            $.ajax({
                url: "project_group/plan_entries",
                method: "POST",
                data: {id: id, pg_plan_entry:{user_id: user_id, hours: hours, project_group_id: pg_id, year: year, month: month}},
                dataType: "json"
              }).done(function(response){
                row.update({total: totalForRow(data)});
              }).fail(function (response) {
            });
        },
    });
    
    var ajaxConfig = {
        type:"GET", //set request type to Position
        contentType: 'application/json; charset=utf-8', //set specific content type
    };
    
    $("#tabulator-example").tabulator("setData","/tabulator_data", {}, ajaxConfig);
    

    function totalForRow(data){
        var total = 0;
        var i;

        for (i = 1; i < 13; i++) { 
            total += Number(data[i]);
        }
        return total;
    };

```
Part of json
```json
[{"id":2,"user_id":1,"user":"test1","pg_id":10,"pg_name":"test","1":5.0,"2":2.0,"3":2.0,"4":2.0,"5":5.0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,
"pe_ids":{"1":9,"2":10,"3":24,"4":27,"5":32,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0},"total":16.0},{"id":3,"user_id":1,"user":"test1","pg_id":15,"pg_name":"test","1":21.0,"2":12.0,"3":5.0,"4":2.0,"5":0,"6":0,"7":12.0,"8":0,"9":0,"10":0,"11":0,"12":0,
"pe_ids":{"1":12,"2":21,"3":22,"4":28,"5":0,"6":0,"7":39,"8":0,"9":0,"10":0,"11":0,"12":0},"total":52.0}]
```

**Comment by MusinAmir** [comment]
I deleted frozen property and now it looks fine
``` javascript
//was
{title: 'Группа проектов', field:'pg_name', headerSort:false, frozen:true}
//now
{title: 'Группа проектов', field:'pg_name', headerSort:false}

**Comment by olifolkerd** [comment]
Thanks for the information.

I will have a look into that and include a patch in the next release

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

Looking into it further,it seems to be a rather unique interaction between the top calcs, frozen column, grouping, and hidden columns, but only in a very specific configuration.

When i have located the exact cause i will let you know.

Cheers

Oli :)

**Comment by MusinAmir** [comment]
Hi @olifolkerd 
Thank you for your attention! Tabulator is awesome!

**Comment by olifolkerd** [comment]
Hey @MusinAmir 

Thanks for the detailed description, it looks like there was a regression with the way the column alignment was being reset when the data was loaded.

I have pushed a fix for this to the 3.5 branch which should be released in the next week.

Cheers

Oli  :)

**Comment by MusinAmir** [comment]
Hey @olifolkerd 
I tried 3.5 tabulator, but seems there is still bug that appears on scrolling.

**Comment by AlexanderSuvorovN** [comment]
Hi Oli,

This problem remains. I'm using Tabulator 3.5 with Chrome. Seems like the issue has relation to ".tabulator-col-resize-handle" -- when I click on the resize handle columns get aligned correctly.

![image](https://user-images.githubusercontent.com/38633357/39098808-94697406-4670-11e8-9c98-e64f69aa7c8d.png)

**Comment by AlexanderSuvorovN** [comment]
This could be also an error in Chrome. I troubleshooted this issue a little and here are my findings:
- There is no such issue in FireFox 59.0.2
- There's no issue when text-overflow is set to "clip" in ".tabulator-row .tabulator-cell" selector

**Comment by olifolkerd** [comment]
Hey @MusinAmir,

Was this related to being zoomed in on the browser like issue #1076?

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @AlexanderSuvorovN 

Your issue is likely due to the table being hidden when the table data is being set and can be fixed by calling the ***redraw*** function when the table is visible. (tabulator needs to be visible to correctly calculate the widths of columns.

The reason the resize handle is fixing the issue is because it triggers a redaraw of that row correcting the visual corruption.

Cheers

Oli :)

**Comment by MusinAmir** [comment]
Hey @olifolkerd
This issue is not related to being zoomed
